import { createElement } from 'react'
import type { ComponentPropsWithoutRef, JSX } from 'react'

const MATH_SYMBOLS: Record<string, string> = {
  '\\alpha': 'α',
  '\\beta': 'β',
  '\\gamma': 'γ',
  '\\delta': 'δ',
  '\\epsilon': 'ε',
  '\\varepsilon': 'ε',
  '\\theta': 'θ',
  '\\vartheta': 'ϑ',
  '\\kappa': 'κ',
  '\\lambda': 'λ',
  '\\mu': 'μ',
  '\\nu': 'ν',
  '\\xi': 'ξ',
  '\\pi': 'π',
  '\\rho': 'ρ',
  '\\sigma': 'σ',
  '\\tau': 'τ',
  '\\phi': 'φ',
  '\\varphi': 'ϕ',
  '\\chi': 'χ',
  '\\psi': 'ψ',
  '\\omega': 'ω',
  '\\Gamma': 'Γ',
  '\\Delta': 'Δ',
  '\\Theta': 'Θ',
  '\\Lambda': 'Λ',
  '\\Pi': 'Π',
  '\\Sigma': 'Σ',
  '\\Phi': 'Φ',
  '\\Psi': 'Ψ',
  '\\Omega': 'Ω',
  '\\times': '×',
  '\\div': '÷',
  '\\cdot': '·',
  '\\pm': '±',
  '\\mp': '∓',
  '\\circ': '∘',
  '\\bullet': '•',
  '\\leq': '≤',
  '\\le': '≤',
  '\\geq': '≥',
  '\\ge': '≥',
  '\\neq': '≠',
  '\\ne': '≠',
  '\\equiv': '≡',
  '\\approx': '≈',
  '\\cong': '≅',
  '\\propto': '∝',
  '\\rightarrow': '→',
  '\\to': '→',
  '\\leftarrow': '←',
  '\\Rightarrow': '⇒',
  '\\leftrightarrow': '↔',
  '\\Leftrightarrow': '⇔',
  '\\mapsto': '↦',
  '\\infty': '∞',
  '\\partial': '∂',
  '\\nabla': '∇',
  '\\forall': '∀',
  '\\exists': '∃',
  '\\neg': '¬',
  '\\land': '∧',
  '\\wedge': '∧',
  '\\lor': '∨',
  '\\vee': '∨',
  '\\oplus': '⊕',
  '\\in': '∈',
  '\\notin': '∉',
  '\\subset': '⊂',
  '\\subseteq': '⊆',
  '\\supseteq': '⊇',
  '\\cup': '∪',
  '\\cap': '∩',
  '\\emptyset': '∅',
  '\\sum': 'Σ',
  '\\prod': '∏',
  '\\int': '∫',
  '\\sqrt': '√',
  '\\angle': '∠',
  '\\perp': '⊥',
  '\\parallel': '∥',
  '\\mid': '∣',
  '\\models': '⊨',
  '\\vdash': '⊢',
  '\\langle': '⟨',
  '\\rangle': '⟩',
  '\\lfloor': '⌊',
  '\\rfloor': '⌋',
  '\\lceil': '⌈',
  '\\rceil': '⌉',
  '\\ldots': '…',
  '\\dots': '…',
  '\\cdots': '⋯',
}

const ACCENTS: Record<string, string> = {
  hat: '\u0302',
  widehat: '\u0302',
  vec: '\u20d7',
  overrightarrow: '\u20d7',
  bar: '\u0304',
  overline: '\u0304',
  tilde: '\u0303',
  dot: '\u0307',
}

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
}

function formatMathFragment(fragment: string): string {
  let value = fragment.replaceAll('$', '')

  value = value.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
  value = value.replace(
    /\\(?:text|mathrm|mathbf|mathit|mathsf|operatorname)\s*\{([^{}]*)\}/g,
    '$1',
  )

  for (let pass = 0; pass < 4; pass += 1) {
    value = value.replace(/\\d?frac\s*\{([^{}]*)\}\s*\{([^{}]*)\}/g, '($1)/($2)')
  }

  value = value.replace(
    /\\(cos|sin|tan|cot|sec|csc|log|ln|exp|max|min|arg|det|dim|deg|gcd|lim|mod|sup|inf)\b/g,
    '$1',
  )

  for (const command of Object.keys(MATH_SYMBOLS).sort((left, right) => right.length - left.length)) {
    value = value.split(command).join(MATH_SYMBOLS[command])
  }

  value = value.replace(
    /\\(hat|widehat|vec|overrightarrow|bar|overline|tilde|dot)\s*\{([^{}]*)\}/g,
    (_match, accent: string, content: string) => `${content}${ACCENTS[accent] ?? ''}`,
  )
  value = value.replace(
    /\\(hat|vec|bar|tilde|dot)\s+(\S)/g,
    (_match, accent: string, content: string) => `${content}${ACCENTS[accent] ?? ''}`,
  )

  value = value
    .replace(/\\[,;:! ]/g, ' ')
    .replace(/\\quad|\\qquad/g, '  ')
    .replace(/\\left|\\right|\\displaystyle|\\limits/g, '')
    .replace(/\^\{([^{}]*)\}/g, '<sup>$1</sup>')
    .replace(/\^([A-Za-z0-9α-ωΓ-Ω*+'+\-])/g, '<sup>$1</sup>')
    .replace(/_\{([^{}]*)\}/g, '<sub>$1</sub>')
    .replace(/_([A-Za-z0-9α-ωΓ-Ω*+'+\-])/g, '<sub>$1</sub>')
    .replace(/[{}]/g, '')
    .replace(/\\\\/g, ' ')
    .replace(/\\([A-Za-z]+)/g, '$1')
    .replace(/\\(.)/g, '$1')

  return value
}

function renderMatrix(body: string): string {
  const rows = body
    .trim()
    .replace(/^(\\\\)+|(\\\\)+$/g, '')
    .split(/\\\\/)
    .map((row) => row.trim())
    .filter(Boolean)
    .map((row) => row.split(/&amp;|&/).map((cell) => formatMathFragment(cell.trim())))

  const columnCount = Math.max(1, ...rows.map((row) => row.length))
  const cells = rows.flatMap((row) => [
    ...row,
    ...Array.from({ length: columnCount - row.length }, () => ''),
  ])

  return `<span class="math-matrix" style="--math-columns:${columnCount}">${cells
    .map((cell) => `<span class="math-matrix__cell">${cell}</span>`)
    .join('')}</span>`
}

/**
 * Converts StudyFlow's deliberately small Markdown/LaTeX subset to HTML.
 *
 * Security boundary: source text is escaped before any formatting happens.
 * Every tag in the returned string is generated by this function; caller HTML
 * can never pass through. Keep `dangerouslySetInnerHTML` confined to MathText.
 */
export function mathTextToSafeHtml(text: string): string {
  let value = escapeHtml(String(text))
  const held: string[] = []
  const hold = (html: string) => `\uE100${held.push(html) - 1}\uE101`

  value = value.replace(/`([^`]+)`/g, (_match, code: string) =>
    hold(`<code class="inline-code">${code}</code>`),
  )

  // Program identifiers must not be mistaken for LaTeX subscripts. Preserve
  // short mathematical forms such as x_i while protecting MPI_Comm_rank.
  value = value.replace(/\b[A-Za-z][A-Za-z0-9]*(?:_[A-Za-z][A-Za-z0-9]*)+\b/g, (identifier) => {
    const parts = identifier.split('_')
    return parts.length === 2 && parts[0].length === 1 && parts[1].length <= 2
      ? identifier
      : hold(`<span class="technical-identifier">${identifier}</span>`)
  })

  value = value.replace(
    /\\begin\{[a-zA-Z]*?matrix\}([\s\S]*?)\\end\{[a-zA-Z]*?matrix\}/g,
    (_match, body: string) => hold(renderMatrix(body)),
  )

  value = formatMathFragment(value).replaceAll('\n', '<br />')

  return value.replace(/\uE100(\d+)\uE101/g, (_match, index: string) => held[Number(index)] ?? '')
}

export type MathTextProps<Element extends keyof JSX.IntrinsicElements = 'span'> = {
  text: string
  as?: Element
  className?: string
  dir?: 'auto' | 'rtl' | 'ltr'
} & Omit<
  ComponentPropsWithoutRef<Element>,
  'as' | 'children' | 'className' | 'dir' | 'dangerouslySetInnerHTML'
>

export function MathText<Element extends keyof JSX.IntrinsicElements = 'span'>({
  text,
  as,
  className,
  dir = 'auto',
  ...props
}: MathTextProps<Element>) {
  return createElement(as ?? 'span', {
    ...props,
    className: ['math-text', className].filter(Boolean).join(' '),
    dir,
    dangerouslySetInnerHTML: { __html: mathTextToSafeHtml(text) },
  })
}
